def configure(conf):
    pass


def build(bld):
    driver_source = bld.path.ant_glob([
        '*.c',
    ])

    bld.objects(
        source=driver_source,
        target='bt_driver',
        defines=['FILE_LOG_COLOR=LOG_COLOR_BLUE'],
        use=[
          'nimble',
          'freertos',
          'fw_includes',
          'root_includes',
        ],
    )
