def configure(conf):
    conf.env.append_value('DEFINES', 'BT_REQUIRE_EARLY_BONDINGS')
    conf.env.append_value('DEFINES', 'BT_NO_REQUIRE_ROOT_KEYS_GEN')


def build(bld):
    driver_source = bld.path.ant_glob([
        '*.c',
    ])

    bld.objects(
        source=driver_source,
        target='bt_driver',
        defines=['FILE_LOG_COLOR=LOG_COLOR_BLUE'],
        use=[
          'nimble',
          'freertos',
          'fw_includes',
          'root_includes',
        ],
    )
