def configure(conf):
    pass


def build(bld):
    sources = bld.path.ant_glob('**/*.c')
    bld.stlib(source=sources,
              target='bt_driver',
              defines=['FILE_LOG_COLOR=LOG_COLOR_BLUE'],
              use=[
                'fw_includes',
                'freertos',
                'root_includes',
              ])
