from waftools.pebble_test import clar


def build(ctx):
    clar(ctx,
         sources_ant_glob=(
             "src/fw/applib/graphics/gtypes.c "
             "src/fw/services/common/compositor/compositor.c "
             "tests/stubs/stubs_modal_manager.c "
             "tests/stubs/stubs_app_state.c "
         ),
         test_sources_ant_glob="test_compositor.c",
         override_includes=['dummy_board'])

# vim:filetype=python
