def configure(conf):
    conf.load('protoc')


def build(bld):
    bld.stlib(features="c cstlib",
              source=bld.path.ant_glob('**/*.proto'),
              includes=bld.path.abspath(),
              target='proto_schemas',
              use='pblibc nanopb idl_includes')

# vim:filetype=python
