from waftools.pebble_test import clar

def build(ctx):

    clar(ctx,
        sources_ant_glob = "src/fw/drivers/qemu/qemu_serial_util.c" \
            " src/fw/util/shared_circular_buffer.c" \
            " tests/fakes/fake_rtc.c",
        test_sources_ant_glob = "test_qemu_serial.c",
        override_includes=['dummy_board'])

    clar(ctx,
        sources_ant_glob="src/fw/drivers/fpc_pinstrap/fpc_pinstrap_snowy.c ",
        test_sources_ant_glob="test_fpc_pinstrap.c",
        override_includes=['fpc_pinstrap_board'])

    clar(ctx,
         sources_ant_glob = "src/fw/drivers/battery/battery_adc_conversion.c",
         test_sources_ant_glob = "test_battery.c")

    clar(ctx,
         sources_ant_glob = "src/fw/drivers/stm32f2/rtc_calibration.c",
         test_sources_ant_glob = "test_rtc_calibration.c",
         override_includes=['rtc_calibration'])

    clar(ctx,
         sources_ant_glob = ('src/fw/drivers/stm32f7/i2c_timingr.c'),
         test_sources_ant_glob = 'test_i2c_timingr.c')

    clar(ctx,
         sources_ant_glob = ('src/fw/drivers/flash/flash_api.c'),
         test_sources_ant_glob = 'test_flash_api.c',
         override_includes=['dummy_board'])

    clar(ctx,
         sources_ant_glob=('src/fw/drivers/flash/flash_erase.c'),
         test_sources_ant_glob='test_flash_erase.c',
         override_includes=['dummy_board'],
         platforms=['tintin'])

# vim:filetype=python
