from waftools.pebble_test import clar

def build(ctx):
   clar(ctx,
        sources_ant_glob = \
            " src/fw/applib/health_service.c" \
            " src/fw/flash_region/flash_region.c" \
            " src/fw/flash_region/filesystem_regions.c" \
            " src/fw/util/base64.c" \
            " src/fw/util/stats.c" \
            " src/fw/util/time/time.c" \
            " src/fw/util/time/mktime.c" \
            " src/fw/services/common/regular_timer.c " \
            " src/fw/services/normal/activity/activity.c" \
            " src/fw/services/normal/activity/activity_metrics.c" \
            " src/fw/services/normal/activity/activity_sessions.c" \
            " src/fw/services/normal/activity/activity_calculators.c" \
            " src/fw/services/normal/activity/hr_util.c" \
            " src/fw/services/normal/filesystem/flash_translation.c" \
            " src/fw/services/normal/filesystem/pfs.c" \
            " src/fw/services/normal/settings/settings_file.c" \
            " src/fw/services/normal/settings/settings_raw_iter.c" \
            " src/fw/shell/normal/prefs.c" \
            " tests/fakes/fake_accel_service.c" \
            " src/fw/util/crc8.c" \
            " src/fw/util/legacy_checksum.c" \
            " tests/fakes/fake_events.c" \
            " tests/fakes/fake_rtc.c" \
            " tests/fakes/fake_spi_flash.c",
        test_sources_ant_glob = "test_activity.c",
        override_includes=['dummy_board'],
        defines=["DUMA_DISABLED", "CAPABILITY_HAS_HEALTH_TRACKING=1",
                 "CAPABILITY_HAS_BUILTIN_HRM=1"])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/util/base64.c" \
            " src/fw/util/crc8.c" \
            " src/fw/util/stats.c" \
            " src/fw/util/time/time.c" \
            " src/fw/util/time/mktime.c" \
            " src/fw/services/normal/activity/activity_insights.c" \
            " src/fw/services/normal/activity/insights_settings.c" \
            " src/fw/services/normal/timeline/metricgroup.c" \
            " src/fw/util/rand/rand.c" \
            " third_party/tinymt/TinyMT/tinymt/tinymt32.c" \
            " tests/fakes/fake_clock.c" \
            " tests/fakes/fake_settings_file.c" \
            " tests/fakes/fake_kernel_services_notifications.c" \
            " tests/fakes/fake_rtc.c",
        test_sources_ant_glob = "test_activity_insights.c",
        override_includes=['dummy_board'])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/activity/kraepelin/kraepelin_algorithm.c" \
            " tests/fakes/fake_rtc.c" \
            " tests/fw/services/activity/step_samples.c" \
            " tests/fw/services/activity/sleep_samples_v1.c" \
            " tests/fw/services/activity/kraepelin_reference/fourier.c" \
            " tests/fw/services/activity/kraepelin_reference/helper_worker.c" \
            " tests/fw/services/activity/kraepelin_reference/ProjectK_worker.c" \
            " tests/fw/services/activity/kraepelin_reference/raw_stats.c",
        defines=['DUMA_DISABLED'],  # DUMA false-positive
        test_sources_ant_glob = "test_kraepelin_algorithm.c",
        override_includes=['dummy_board'])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/flash_region/flash_region.c" \
            " src/fw/flash_region/filesystem_regions.c" \
            " src/fw/util/base64.c" \
            " src/fw/util/crc8.c" \
            " src/fw/util/shared_circular_buffer.c" \
            " src/fw/util/time/time.c" \
            " src/fw/util/time/mktime.c" \
            " src/fw/services/common/regular_timer.c " \
            " src/fw/services/normal/activity/kraepelin/activity_algorithm_kraepelin.c" \
            " src/fw/services/normal/filesystem/flash_translation.c" \
            " src/fw/services/normal/filesystem/pfs.c" \
            " src/fw/services/normal/settings/settings_file.c" \
            " src/fw/services/normal/settings/settings_raw_iter.c" \
            " tests/fakes/fake_accel_service.c" \
            " src/fw/util/legacy_checksum.c" \
            " tests/fakes/fake_events.c" \
            " tests/fakes/fake_rtc.c" \
            " tests/fakes/fake_spi_flash.c",
        test_sources_ant_glob = "test_activity_algorithm_kraepelin.c",
        defines=['DUMA_DISABLED'],  # DUMA false-positive, therefore disabled
        override_includes=['dummy_board'])


   clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/activity/health_util.c",
        test_sources_ant_glob = "test_health_util.c",
        override_includes=['dummy_board'])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/activity/hr_util.c",
        test_sources_ant_glob = "test_hr_util.c",
        override_includes=['dummy_board'])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/activity/activity_calculators.c" \
            " src/fw/services/normal/activity/hr_util.c" \
            " src/fw/services/normal/activity/workout_service.c" \
            " tests/fakes/fake_events.c" \
            " tests/fakes/fake_rtc.c",
        test_sources_ant_glob = "test_workout_service.c",
        defines=["CAPABILITY_HAS_BUILTIN_HRM=1"],
        override_includes=['dummy_board'])

   clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/activity/activity_calculators.c",
        test_sources_ant_glob = "test_activity_calculators.c",
        override_includes=['dummy_board'])

# vim:filetype=python
