project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

"files": [
  {
    source: "resources/normal/base/lang/tintin.pot",
    translation: "resources/normal/base/lang/%locale_with_underscore%/tintin.po"
  }
]
