from waftools.pebble_test import clar

def build(ctx):
    clar(ctx,
        sources_ant_glob = " src/fw/shell/normal/system_app_state_machine.c",
        test_sources_ant_glob = "test_normal_system_app_state_machine.c")

    clar(ctx,
        sources_ant_glob = " src/fw/shell/normal/battery_ui_fsm.c"
                           " src/fw/services/common/battery/battery_curve.c",
        test_sources_ant_glob = 'test_battery_ui_fsm.c',
        override_includes=['dummy_board'],
        platforms = ['snowy'])

    clar(ctx,
        sources_ant_glob = " src/fw/shell/normal/display_calibration_prompt.c",
        test_sources_ant_glob = 'test_display_calibration_prompt.c',
        override_includes=['dummy_board'],
        platforms = ['spalding'])
# vim:filetype=python
