def options(opt):
    pass

def configure(conf):
    conf.recurse('nanopb')


def build(bld):
    bld(export_includes=bld.path.get_bld().abspath(), name='idl_includes')
    bld.recurse('nanopb')


# vim:filetype=python
