from waflib import Task
from waflib.TaskGen import feature, before_method


def build(bld):
    sources = bld.path.ant_glob('*.c')
    bld.program(source=sources,
                target='sdl-example',
                defines=['main=app_main'],
                use=['applib_sdl', 'fw_includes'])

# vim:filetype=python
