#!/bin/bash

TARGET="target extended-remote | openocd -f openocd.cfg \
  -c \"gdb_port pipe; init; reset halt;\""

arm-none-eabi-gdb build/tintin_boot.elf \
  -ex "${TARGET}" \
  -ex "break boot_main" \
  -ex "continue"

# vim:filetype=sh
