from waftools.pebble_test import clar

def build(ctx):
    clar(ctx,
        sources_ant_glob = \
            " src/fw/services/normal/analytics/analytics_heartbeat.c" \
            " src/fw/services/normal/analytics/analytics_metric.c" \
            " tests/fakes/fake_rtc.c" \
            " src/fw/util/rand/rand.c" \
            " third_party/tinymt/TinyMT/tinymt/tinymt32.c",
        test_sources_ant_glob = "test_analytics_heartbeat.c")

    clar(ctx,
         sources_ant_glob=(
            " src/fw/services/normal/analytics/analytics_event.c"
         ),
         test_sources_ant_glob="test_analytics_event.c",
         override_includes=['dummy_board'])
