import waftools.cc2564_service_pack_convert

def configure(conf):
    pass


def build(bld):
    service_pack_bin_bld_node = bld.srcnode.get_bld().make_node(
        'resources/common/raw/bt_patch.bin')
    service_pack_bts = '../../vendor/ti-service-packs/initscripts/TIInit_6.7.16.bts'
    bld(rule=waftools.cc2564_service_pack_convert.wafrule,
        source=service_pack_bts,
        target=service_pack_bin_bld_node)
    bld.DYNAMIC_RESOURCES.append(service_pack_bin_bld_node)
    
    chipset_source = bld.path.ant_glob([
        '*.c',
    ])

    bld.objects(
        source=chipset_source,
        target='bt_chipset_driver',
        defines=['FILE_LOG_COLOR=LOG_COLOR_BLUE'],
        use=[
          'fw_includes',
          'freertos',
          'root_includes',
        ],
    )
