/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


//
// AUTOGENERATED
// DO NOT MODIFY
//

#include "resource/resource_storage_file.h"
#include "resource/resource_ids.auto.h"

const uint32_t g_num_file_resource_stores = 2;

const FileResourceData g_file_resource_stores[] = {
  { RESOURCE_ID_PUG, RESOURCE_ID_PUG, (RESOURCE_ID_PUG - 1), "pug" },
  { RESOURCE_ID_STRINGS, RESOURCE_ID_DROID_SERIF_28_BOLD_EXTENDED, (RESOURCE_ID_STRINGS - 1), "lang" },
};
