#define BOARD_UART_TX_PIN 27

#define BOARD_QSPI_SCK_PIN 19
#define BOARD_QSPI_SCN_PIN 17
#define BOARD_QSPI_IO0_PIN 20
#define BOARD_QSPI_IO1_PIN 21
#define BOARD_QSPI_IO2_PIN 22
#define BOARD_QSPI_IO3_PIN 23

#define BOARD_DISP_DISP_PORT NRF_P0
#define BOARD_DISP_DISP_PIN 4
#define BOARD_DISP_CS_PORT NRF_P1
#define BOARD_DISP_CS_PIN 3
#define BOARD_DISP_SCK_PIN 6
#define BOARD_DISP_MOSI_PIN 8

#define BOARD_BUTTON_BACK_PORT NRF_P0
#define BOARD_BUTTON_BACK_PIN 28
#define BOARD_BUTTON_UP_PORT NRF_P0
#define BOARD_BUTTON_UP_PIN 29
#define BOARD_BUTTON_SELECT_PORT NRF_P0
#define BOARD_BUTTON_SELECT_PIN 30
#define BOARD_BUTTON_DOWN_PORT NRF_P0
#define BOARD_BUTTON_DOWN_PIN 31

#define BOARD_PMIC_I2C 1
#define BOARD_PMIC_I2C_SCL_PIN 14
#define BOARD_PMIC_I2C_SDA_PIN 15

#define BOARD_FLASH_JEDEC_ID 0xc86019
