from waftools.pebble_test import clar

def build(ctx):
    clar(ctx,
        sources_ant_glob = "src/fw/console/cobs.c",
        test_sources_ant_glob = "test_cobs_decode.c")

    clar(ctx,
        sources_ant_glob = "src/fw/console/cobs.c",
        test_sources_ant_glob = "test_cobs_encode.c")

# vim:filetype=python

