import os

def configure(conf):
    pass

def build(bld):
    if bld.variant in ('test', 'test_rocky_emx', 'pdc2png'):
        bld.recurse('pdc2png')

    if bld.variant == 'test':
        bld.recurse('tests')

    # This variant is not supported yet, but can be used to build all tools
    if bld.variant == 'tools':
        tool_dirs = [os.path.dirname(f.abspath()) for f in bld.path.ant_glob('**/wscript')]
        for dir in tool_dirs:
            bld.recurse(dir)

# vim:filetype=python
