<?php
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'PebbleCpplintLinter' => 'cpplint/PebbleCpplintLinter.php',
    'PebbleCppcheckLinter' => 'cppcheck/PebbleCppcheckLinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'PebbleCpplintLinter' => 'ArcanistExternalLinter',
    'PebbleCppcheckLinter' => 'ArcanistExternalLinter',
  ),
));
