from waftools.pebble_test import clar

def build(ctx):
    clar(ctx,
         sources_ant_glob=(
             " src/fw/shell/system_theme.c"
         ),
         test_sources_ant_glob="test_system_theme.c")

# vim:filetype=python
